# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ffd0bcdf6297c4140da3125b06d7ae65d6b70a44268e9db5e430c62843498038ae930c348c313ebe08f2549775a2aa55cb74c7b34d40a2edfb010f275347b0

test:
  secret_key_base: 42a2a2cbea2b5c1c9039f04e9fa7d66129ec9ae6758dd4061255fa105a814acfa952099dfed4b95ca4f45ed9b47f5cabefee8bbc478f0afcd30ac55c0f4bac74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
